[package]
name = "test_utils"
description = "Test utilities to make e2e/integration testing easier"
version = "0.1.0"
edition = "2024"

[dependencies]
gix = { workspace = true }
anyhow = { workspace = true }
tempfile = "=3.23.0"
