# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark = "catppuccin-macchiato"
light = "catppuccin-macchiato"

[manager]
cwd = { fg = "#8bd5ca" }
hovered = { fg = "#24273a", bg = "#8aadf4" }
preview_hovered = { underline = true }
