settings.cargo.binstall = true
settings.experimental = true

# Pick tools that renovate can manage updates for. See:
# https://docs.renovatebot.com/modules/manager/mise/
[tools]

"aqua:fish-shell/fish-shell" = "4.4.0"
"cargo:bacon" = "3.19.0"
"cargo:cargo-nextest" = "0.9.117"
"cargo:eza" = "0.23.3"
"cargo:presenterm" = "0.15.1"
"npm:@anthropic-ai/claude-code" = "2.1.30"
"npm:@typescript/native-preview" = "7.0.0-dev.20260203.1"
"npm:oxlint" = "1.43.0"
"npm:yaml-language-server" = "1.19.2"
"pipx:awslabs.cloudwatch-mcp-server" = "0.0.19"
"ubi:BurntSushi/ripgrep" = { version = "15.1.0", exe = "rg" }
"ubi:JohnnyMorganz/stylua" = "2.3.1"
"ubi:MordechaiHadad/bob" = "4.1.6"
"ubi:aaronriekenberg/rust-parallel" = "1.21.0"
"ubi:ajeetdsouza/zoxide" = "0.9.9"
"ubi:ankitpokhrel/jira-cli" = { version = "1.7.0", exe = "jira" }
"ubi:ast-grep/ast-grep" = "0.40.5"
"ubi:atuinsh/atuin" = { version = "18.11.0", matching_regex = ".tar.gz$" }
"ubi:cargo-bins/cargo-binstall" = "1.17.4"
"ubi:charmbracelet/glow" = "2.1.1"
"ubi:chmln/sd" = "1.0.0"
"ubi:dandavison/delta" = "0.18.2"
"ubi:hadolint/hadolint" = "2.14.0"
"ubi:jesseduffield/lazydocker" = "0.24.4"
"ubi:junegunn/fzf" = "0.67.0"
"ubi:k1LoW/git-wt" = "0.19.0"
"ubi:ouch-org/ouch" = "0.6.1"
"ubi:pranshuparmar/witr" = "0.2.6"
"ubi:rvben/rumdl" = "0.1.14"
"ubi:sharkdp/bat" = "0.26.1"
"ubi:sharkdp/fd" = "10.3.0"
"ubi:sharkdp/hyperfine" = "1.20.0"
"ubi:starship/starship" = "1.24.2"
"ubi:tekumara/typos-lsp" = "0.1.48"
"ubi:tree-sitter/tree-sitter" = "0.26.5"
"ubi:watchexec/watchexec" = "2.3.3"
actionlint = "1.7.10"
dotenv-linter = "4.0.0"
jq = "1.8.1"
shfmt = "3.12.0"
typos = "1.43.3"
ubi = "0.8.1"
uv = "0.10.0"


[tools."ubi:gitlab-org/cli"]
version = "1.82.0"
provider = "gitlab"
exe = "glab"
postinstall = """
mkdir -p ~/.config/fish/completions
glab completion -s fish > ~/.config/fish/completions/glab.fish
"""

[tools.github-cli]
version = "2.86.0"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- gh completion --shell fish > ~/.config/fish/completions/gh.fish
"""

[tools.yq]
version = "4.52.2"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- yq completion fish > ~/.config/fish/completions/yq.fish
"""

[tools."ubi:ducaale/xh"]
version = "0.25.3"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- xh --generate complete-fish > ~/.config/fish/completions/xh.fish
"""
