settings.cargo.binstall = true

# Pick tools that renovate can manage updates for. See:
# https://docs.renovatebot.com/modules/manager/mise/
[tools]

"cargo:bacon" = "3.19.0"
"cargo:eza" = "0.23.3"
"ubi:BurntSushi/ripgrep" = { version = "15.1.0", exe = "rg" }
"ubi:JohnnyMorganz/stylua" = "2.3.1"
"ubi:aaronriekenberg/rust-parallel" = "1.20.0"
"ubi:ajeetdsouza/zoxide" = "0.9.8"
"ubi:ankitpokhrel/jira-cli" = { version = "1.7.0", exe = "jira" }
"ubi:atuinsh/atuin" = { version = "18.10.0", matching_regex = ".tar.gz$" }
"ubi:cargo-bins/cargo-binstall" = "1.16.4"
"ubi:charmbracelet/glow" = "2.1.1"
"ubi:chmln/sd" = "1.0.0"
"ubi:dandavison/delta" = "0.18.2"
"ubi:gitlab-org/cli" = { version = "1.80.0", provider = "gitlab", exe = "glab" }
"ubi:jesseduffield/lazydocker" = "0.24.2"
"ubi:junegunn/fzf" = "0.67.0"
"ubi:sharkdp/bat" = "0.26.1"
"ubi:sharkdp/fd" = "10.3.0"
"ubi:sharkdp/hyperfine" = "1.20.0"
"ubi:starship/starship" = "1.24.1"
"ubi:tree-sitter/tree-sitter" = "0.26.3"
"ubi:watchexec/watchexec" = "2.3.2"

jq = "1.8.1"
actionlint = "1.7.9"
dotenv-linter = "4.0.0"
ubi = "0.8.1"
"aqua:fish-shell/fish-shell" = "4.2.1"
claude-code = { version = "2.0.57", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-x64/claude"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/stable" }

[tools.github-cli]
version = "2.83.2"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- gh completion --shell fish > ~/.config/fish/completions/gh.fish
"""

[tools.yq]
version = "4.50.1"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- yq completion fish > ~/.config/fish/completions/yq.fish
"""

[tools."ubi:ducaale/xh"]
version = "0.25.3"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- xh --generate complete-fish > ~/.config/fish/completions/xh.fish
"""
