settings.cargo.binstall = true

# Pick tools that renovate can manage updates for. See:
# https://docs.renovatebot.com/modules/manager/mise/
[tools]

"aqua:fish-shell/fish-shell" = "4.3.2"
"cargo:bacon" = "3.19.0"
"cargo:eza" = "0.23.3"
"cargo:presenterm" = "0.15.1"
"cargo:rumdl" = "0.0.207"
"npm:@anthropic-ai/claude-code" = "2.0.76"
"ubi:BurntSushi/ripgrep" = { version = "15.1.0", exe = "rg" }
"ubi:JohnnyMorganz/stylua" = "2.3.1"
"ubi:aaronriekenberg/rust-parallel" = "1.20.0"
"ubi:ajeetdsouza/zoxide" = "0.9.8"
"ubi:ankitpokhrel/jira-cli" = { version = "1.7.0", exe = "jira" }
"ubi:atuinsh/atuin" = { version = "18.10.0", matching_regex = ".tar.gz$" }
"ubi:cargo-bins/cargo-binstall" = "1.16.6"
"ubi:charmbracelet/glow" = "2.1.1"
"ubi:chmln/sd" = "1.0.0"
"ubi:dandavison/delta" = "0.18.2"
"ubi:gitlab-org/cli" = { version = "1.80.4", provider = "gitlab", exe = "glab" }
"ubi:jesseduffield/lazydocker" = "0.24.3"
"ubi:junegunn/fzf" = "0.67.0"
"ubi:pranshuparmar/witr" = "0.1.5"
"ubi:sharkdp/bat" = "0.26.1"
"ubi:sharkdp/fd" = "10.3.0"
"ubi:sharkdp/hyperfine" = "1.20.0"
"ubi:starship/starship" = "1.24.2"
"ubi:tree-sitter/tree-sitter" = "0.26.3"
"ubi:watchexec/watchexec" = "2.3.2"
actionlint = "1.7.10"
dotenv-linter = "4.0.0"
jq = "1.8.1"
ubi = "0.8.1"

[tools.github-cli]
version = "2.83.2"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- gh completion --shell fish > ~/.config/fish/completions/gh.fish
"""

[tools.yq]
version = "4.50.1"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- yq completion fish > ~/.config/fish/completions/yq.fish
"""

[tools."ubi:ducaale/xh"]
version = "0.25.3"
postinstall = """
mkdir -p ~/.config/fish/completions
mise exec -- xh --generate complete-fish > ~/.config/fish/completions/xh.fish
"""
